spring:
  application:
    name: YuForum
  profiles:
    active: pro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jdy200255
  mail:
    host: smtp.qq.com
    username: 2475058223@qq.com
    password: awxesgjpwgikdjjc
    port: 587
    properties:
      mail:
        smtp:
          ssl:
            enable: false
            required: false
        debug: false
  redis:
    # 默认连接数据库
    database: 0
    # 连接超时时间
    timeout: 10000
    jedis:
      pool:
        max-wait: 3000
server:
  port: 80
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/forum?serverTimezone=GMT%2B8
---
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://180.76.101.239:3306/forum?serverTimezone=GMT%2B8
server:
  port: 8082
---
